local myaddon = ...
local L = LibStub("AceLocale-3.0"):NewLocale(myaddon, "zhTW", false)

if not L then return end

-- Isle of Giants  (Rare)
L["War-God Dokah"] = "|cFFFFFFFFWar-God Dokah|r"
L["War-God Dokah Note"] = "包含 60-80 |cFFFFFFFF銅幣|r 以及聲望通貨。"

-- The Jade Forest (Treasure)
L["Ancient Pandaren Tea Pot"] = "|cFFFFFFFFAncient Pandaren Tea Pot|r"
L["Ancient Pandaren Tea Pot Note"] = "包含|cFF9D9D9DAncient Pandaren Tea Pot|r, cost |cFFFFFFFF10金幣。|r"
L["Lucky Pandaren Coin"] = "|cFFFFFFFFLucky Pandaren Coin|r"
L["Lucky Pandaren Coin Note"] = "包含|cFF9D9D9DLucky Pandaren Coin|r, cost |cFFFFFFFF10金幣。|r"
L["Pandaren Ritual Stone"] = "|cFFFFFFFFPandaren Ritual Stone|r"
L["Pandaren Ritual Stone Note"] = "包含|cFF9D9D9DPandaren Ritual Stone|r, cost |cFFFFFFFF10金幣。|r"
L["Ship's Locker"] = "|cFFFFFFFFShip's Locker|r"
L["Ship's Locker Note"] = "包含11|cFFFFFFFF青銅幣|r, chest in the hold of a ship."

L["Order"] = "|cFFFFFFFF雲蛟衛軍需官|r"
L["Order Note"] = "兌換|cFFFFFFFF次級好運符|r 依據聲望。"
L["August"] = "|cFFFFFFFFThe August Celestials|r"
L["August Note"] = "兌換|cFFFFFFFF次級好運符|r 依據聲望。"

L["Chest of Supplies"] = "|cFFFFFFFFChest of Supplies|r"
L["Chest of Supplies Note"] = "包含|cFFFFFFFF10金幣。|r"
L["Offering of Rememberance"] = "|cFFFFFFFFOffering of Rememberance|r"
L["Offering of Rememberance Note"] = "包含|cFFFFFFFF11金幣。|r"
L["Stash of Gems"] = "|cFFFFFFFFStash of Gems|r"
L["Stash of Gems Note"] = "包含50-55|cFFFFFFFF青銅幣|r，以及|cFFFFFFFF7金幣。|r"
L["Ancient Pandaren Mining Pick"] = "|cFFFFFFFFAncient Pandaren Mining Pick|r"
L["Ancient Pandaren Mining Pick Note"] = "包含50-55|cFFFFFFFF青銅幣|r，以及|cFFFFFFFF7金幣。|r"

-- The Jade Forest (Rare)
L["Kor'nas Nightsavage"] = "|cFFFFFFFFKor'nas Nightsavage|r"
L["Kor'nas Nightsavage Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Krax'ik"] = "|cFFFFFFFFKrax'ik|r"
L["Krax'ik Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Sarnak"] = "|cFFFFFFFFSarnak|r"
L["Sarnak Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Mister Ferocious"] = "|cFFFFFFFFMister Ferocious|r"
L["Mister Ferocious Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Morgrinn Crackfang"] = "|cFFFFFFFFMorgrinn Crackfang|r"
L["Morgrinn Crackfang Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Aethis"] = "|cFFFFFFFFAethis|r"
L["Aethis Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Urobi the Walker"] = "|cFFFFFFFFUrobi the Walker|r"
L["Urobi the Walker Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Ferdinand"] = "|cFFFFFFFFFerdinand|r"
L["Ferdinand Note"] = "包含50-70|cFFFFFFFF青銅幣|r."

-- Valley of the Four Winds (Treasure)
L["Virmen Treasure Cache"] = "|cFFFFFFFFVirmen Treasure Cache|r"
L["Virmen Treasure Cache Note"] = "包含17|cFFFFFFFF青銅幣|r，以及絲線。箱子在洞穴。"
L["The Hammer of Folly"] = "|cFFFFFFFFThe Hammer of Folly|r"
L["The Hammer of Folly Note"] = "包含|cFF9D9D9DThe Hammer of Folly|r, cost |cFFFFFFFF100金幣。|r"

-- Valley of the Four Winds (Rare)
L["Blackhoof"] = "|cFFFFFFFFBlackhoof|r"
L["Blackhoof Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Jonn-Dar"] = "|cFFFFFFFFJonn-Dar|r"
L["Jonn-Dar Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Nasra Spothide"] = "|cFFFFFFFFNasra Spothide|r"
L["Nasra Spothide Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Sele'na"] = "|cFFFFFFFFSele'na|r"
L["Sele'na Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Bonobos"] = "|cFFFFFFFFBonobos|r"
L["Bonobos Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Nal'lak the Ripper"] = "|cFFFFFFFFNal'lak the Ripper|r"
L["Nal'lak the Ripper Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Salyin Warscout"] = "|cFFFFFFFFSalyin Warscout|r"
L["Salyin Warscout Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Sulik'shor"] = "|cFFFFFFFFSulik'shor|r"
L["Sulik'shor Note"] = "包含50-70|cFFFFFFFF青銅幣|r."

-- Kun-Lai Summit (Treasure)
L["Hozen Treasure Cache"] = "|cFFFFFFFFHozen Treasure Cache|r"
L["Hozen Treasure Cache Note"] = "包含11|cFFFFFFFF青銅幣|r, chest in a cave."
L["Stolen Sprite Treasure"] = "|cFFFFFFFFStolen Sprite Treasure|r"
L["Stolen Sprite Treasure Note"] = "包含11|cFFFFFFFF青銅幣|r, chest in a cave."
L["Statue of Xuen"] = "|cFFFFFFFFStatue of Xuen|r"
L["Statue of Xuen Note"] = "包含|cFF9D9D9DStatue of Xuen|r, cost |cFFFFFFFF100金幣。|r"
L["Lost Adventurer's Belongings"] = "|cFFFFFFFFLost Adventurer's Belongings|r"
L["Lost Adventurer's Belongings Note"] = "包含30-40|cFFFFFFFF青銅幣|r."
L["Rikktik's Tiny Chest"] = "|cFFFFFFFFRikktik's Tiny Chest|r"
L["Rikktik's Tiny Chest Note"] = "包含|cFF9D9D9DRikktik's Tiny Chest|r, cost |cFFFFFFFF105 gold|r and |cFFFFFFFFBronze.|r"
L["Ancient Mogu Tablet"] = "|cFFFFFFFFAncient Mogu Tablet|r"
L["Ancient Mogu Tablet Note"] = "包含|cFF9D9D9DAncient Mogu Tablet|r, cost |cFFFFFFFF95 gold|r, chest in a cave."
L["Terracotta Head"] = "|cFFFFFFFFTerracotta Head|r"
L["Terracotta Head Note"] = "包含|cFF9D9D9DTerracotta Head|r, cost |cFFFFFFFF100金幣。|r"

-- Kun-Lai Summit (Rare)
L["Ahone the Wanderer"] = "|cFFFFFFFFAhone the Wanderer|r"
L["Ahone the Wanderer Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Havak"] = "|cFFFFFFFFHavak|r"
L["Havak Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Nessos the Oracle"] = "|cFFFFFFFFNessos the Oracle|r"
L["Nessos the Oracle Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Ski'thik"] = "|cFFFFFFFFSki'thik|r"
L["Ski'thik Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Borginn Darkfist"] = "|cFFFFFFFFBorginn Darkfist|r"
L["Borginn Darkfist Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Korda Torros"] = "|cFFFFFFFFKorda Torros|r"
L["Korda Torros Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Scritch"] = "|cFFFFFFFFScritch|r"
L["Scritch Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Zai the Outcast"] = "|cFFFFFFFFZai the Outcast|r"
L["Zai the Outcast Note"] = "包含50-70|cFFFFFFFF青銅幣|r."

L["Mo-Mo's Treasure Chest"] = "|cFFFFFFFFMo-Mo's Treasure Chest|r"
L["Mo-Mo's Treasure Chest Note"] = "包含 65-75 |cFFFFFFFF青銅幣|r，以及絲線。"

-- Townlong Steppes (Treasure)
L["Fragment of Dread"] = "|cFFFFFFFFFragment of Dread|r"
L["Fragment of Dread Note"] = "包含|cFF9D9D9DFragment of Dread|r, cost |cFFFFFFFF90 gold|r, chest in a cave."
L["Hardened Sap of Kri'vess"] = "|cFFFFFFFFHardened Sap of Kri'vess|r"
L["Hardened Sap of Kri'vess Note"] = "包含|cFF9D9D9DHardened Sap of Kri'vess|r, cost |cFFFFFFFF110金幣。|r."
L["Amber Encased Moth"] = "|cFFFFFFFFAmber Encased Moth|r"
L["Amber Encased Moth Note"] = "包含|cFF9D9D9DAmber Encased Moth|r, cost |cFFFFFFFF105金幣。|r."
L["Abandoned Crate of Goods"] = "|cFFFFFFFFAbandoned Crate of Goods|r"
L["Abandoned Crate of Goods Note"] = "包含40-50|cFFFFFFFF青銅幣|r，以及絲線。chest under awning."

L["Shado"] = "|cFFFFFFFF影潘|r"
L["Shado Note"] = "兌換|cFFFFFFFF次級好運符|r 依據聲望。"

-- Townlong Steppes (Rare)
L["The Yowler"] = "|cFFFFFFFFThe Yowler|r"
L["The Yowler Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Lith'ik the Stalker"] = "|cFFFFFFFFLith'ik the Stalker|r"
L["Lith'ik the Stalker Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Kah'tir"] = "|cFFFFFFFFKah'tir|r"
L["Kah'tir Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Siltriss the Sharpener"] = "|cFFFFFFFFSiltriss the Sharpener|r"
L["Siltriss the Sharpener Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Eshelon"] = "|cFFFFFFFFEshelon|r"
L["Eshelon Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Norlaxx"] = "|cFFFFFFFFNorlaxx|r"
L["Norlaxx Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Yul Wildpaw"] = "|cFFFFFFFFYul Wildpaw|r"
L["Yul Wildpaw Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Lon the Bull"] = "|cFFFFFFFFLon the Bull|r"
L["Lon the Bull Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Huggalon the Heart Watcher"] = "|cFFFFFFFFHuggalon the Heart Watcher|r"
L["Huggalon the Heart Watcher Note"] = "包含50-70|cFFFFFFFF青銅幣|r."

-- Vale of Eternal Blossoms (Rare)
L["Major Nanners"] = "|cFFFFFFFFMajor Nanners|r"
L["Major Nanners Note"] = "包含50-60|cFFFFFFFF青銅幣|r."
L["Kal'tik the Blight"] = "|cFFFFFFFFKal'tik the Blight|r"
L["Kal'tik the Blight Note"] = "包含50-60|cFFFFFFFF青銅幣|r."
L["Urgolax"] = "|cFFFFFFFFUrgolax|r"
L["Urgolax Note"] = "包含50-60|cFFFFFFFF青銅幣|r."
L["Moldo One-Eye"] = "|cFFFFFFFFMoldo One-Eye|r"
L["Moldo One-Eye Note"] = "包含50-60|cFFFFFFFF青銅幣|r."
L["Sahn Tidehunter"] = "|cFFFFFFFFSahn Tidehunter|r"
L["Sahn Tidehunter Note"] = "包含50-60|cFFFFFFFF青銅幣|r."
L["Kang the Soul Thief"] = "|cFFFFFFFFKang the Soul Thief|r"
L["Kang the Soul Thief Note"] = "包含50-60|cFFFFFFFF青銅幣|r."
L["Ai-Ran the Shifting Cloud"] = "|cFFFFFFFFAi-Ran the Shifting Cloud|r"
L["Ai-Ran the Shifting Cloud Note"] = "包含50-60|cFFFFFFFF青銅幣|r."
L["Yorik Sharpeye"] = "|cFFFFFFFFYorik Sharpeye|r"
L["Yorik Sharpeye Note"] = "包含50-60|cFFFFFFFF青銅幣|r."
L["Aetha"] = "|cFFFFFFFFAetha|r"
L["Aetha Note"] = "包含50-60|cFFFFFFFF青銅幣|r."
L["Bai-Jin the Butcher"] = "|cFFFFFFFFBai-Jin the Butcher|r"
L["Bai-Jin the Butcher Note"] = "包含50-60|cFFFFFFFF青銅幣|r."
L["Baolai the Immolator"] = "|cFFFFFFFFBaolai the Immolator|r"
L["Baolai the Immolator Note"] = "包含50-60|cFFFFFFFF青銅幣|r."
L["Bloodtip"] = "|cFFFFFFFFBloodtip|r"
L["Bloodtip Note"] = "包含50-60|cFFFFFFFF青銅幣|r."
L["Huo-Shang"] = "|cFFFFFFFFHuo-Shang|r"
L["Huo-Shang Note"] = "包含50-60|cFFFFFFFF青銅幣|r."
L["Gaohun the Soul-Severer"] = "|cFFFFFFFFGaohun the Soul-Severer|r"
L["Gaohun the Soul-Severer Note"] = "包含50-60|cFFFFFFFF青銅幣|r."
L["Cracklefang"] = "|cFFFFFFFFCracklefang|r"
L["Cracklefang Note"] = "包含50-60|cFFFFFFFF青銅幣|r."
L["General Temuja"] = "|cFFFFFFFFGeneral Temuja|r"
L["General Temuja Note"] = "包含50-60|cFFFFFFFF青銅幣|r."
L["Gochao the Ironfist"] = "|cFFFFFFFFGochao the Ironfist|r"
L["Gochao the Ironfist Note"] = "包含50-60|cFFFFFFFF青銅幣|r."
L["Kri'chon"] = "|cFFFFFFFFKri'chon|r"
L["Kri'chon Note"] = "包含50-60|cFFFFFFFF青銅幣|r."
L["Quid"] = "|cFFFFFFFFQuid|r"
L["Quid Note"] = "包含50-60|cFFFFFFFF青銅幣|r."
L["Shadowmaster Sydow"] = "|cFFFFFFFFShadowmaster Sydow|r"
L["Shadowmaster Sydow Note"] = "包含50-60|cFFFFFFFF青銅幣|r."
L["Spirit of Lao-Fe"] = "|cFFFFFFFFSpirit of Lao-Fe|r"
L["Spirit of Lao-Fe Note"] = "包含50-60|cFFFFFFFF青銅幣|r."
L["Vicejaw"] = "|cFFFFFFFFVicejaw|r"
L["Vicejaw Note"] = "包含50-60|cFFFFFFFF青銅幣|r."
L["Vyraxxis"] = "|cFFFFFFFFVyraxxis|r"
L["Vyraxxis Note"] = "包含50-60|cFFFFFFFF青銅幣|r."
L["Wulon"] = "|cFFFFFFFFWulon|r"
L["Wulon Note"] = "包含50-60|cFFFFFFFF青銅幣|r."

L["Lotus"] = "|cFFFFFFFF金蓮會|r"
L["Lotus Note"] = "兌換|cFFFFFFFF次級好運符|r 依據聲望。"

-- Krasarang Wilds (Treasure)
L["Saurok Stone Tablet"] = "|cFFFFFFFFSaurok Stone Tablet|r"
L["Saurok Stone Tablet Note"] = "包含|cFF9D9D9DSaurok Stone Tablet|r, cost |cFFFFFFFF100金幣。|r."

L["Anglers"] = "|cFFFFFFFFThe Anglers|r"
L["Anglers Note"] = "兌換|cFFFFFFFF次級好運符|r 依據聲望。"
L["Alliance"] = "|cFFFFFFFFAlliance|r"
L["Alliance Note"] = "兌換|cFFFFFFFF次級好運符|r 依據聲望。"
L["Horde"] = "|cFFFFFFFFHorde|r"
L["Horde Note"] = "兌換|cFFFFFFFF次級好運符|r 依據聲望。"

-- Krasarang Wilds (Rare)
L["Arness the Scale"] = "|cFFFFFFFFArness the Scale|r"
L["Arness the Scale Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Gaarn the Toxic"] = "|cFFFFFFFFGaarn the Toxic|r"
L["Gaarn the Toxic Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Qu'nas"] = "|cFFFFFFFFQu'nas|r"
L["Qu'nas Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Spriggin"] = "|cFFFFFFFFSpriggin|r"
L["Spriggin Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Cournith Waterstrider"] = "|cFFFFFFFFCournith Waterstrider|r"
L["Cournith Waterstrider Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Go-Kan"] = "|cFFFFFFFFGo-Kan|r"
L["Go-Kan Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Ruun Ghostpaw"] = "|cFFFFFFFFRuun Ghostpaw|r"
L["Ruun Ghostpaw Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Torik-Ethis"] = "|cFFFFFFFFTorik-Ethis|r"
L["Torik-Ethis Note"] = "包含50-70|cFFFFFFFF青銅幣|r."

L["Dalan Nightbreaker"] = "|cFFFFFFFFDalan Nightbreaker|r"
L["Dalan Nightbreaker Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Disha Fearwarden"] = "|cFFFFFFFFDisha Fearwarden|r"
L["Disha Fearwarden Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Kar Warmaker"] = "|cFFFFFFFFKar Warmaker|r"
L["Kar Warmaker Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Mavis Harms"] = "|cFFFFFFFFMavis Harms|r"
L["Mavis Harms Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Muerta"] = "|cFFFFFFFFMuerta|r"
L["Muerta Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Ubunti the Shade"] = "|cFFFFFFFFUbunti the Shade|r"
L["Ubunti the Shade Note"] = "包含50-70|cFFFFFFFF青銅幣|r."

-- Dread Wastes (Rare)
L["Ik-Ik the Nimble"] = "|cFFFFFFFFIk-Ik the Nimble|r"
L["Ik-Ik the Nimble Note"] = "包含60-80|cFFFFFFFF青銅幣|r."
L["Gar'lok"] = "|cFFFFFFFFGar'lok|r"
L["Gar'lok Note"] = "包含60-80|cFFFFFFFF青銅幣|r."
L["Krol the Blade"] = "|cFFFFFFFFKrol the Blade|r"
L["Krol the Blade Note"] = "包含60-80|cFFFFFFFF青銅幣|r."
L["Omnis Grinlok"] = "|cFFFFFFFFOmnis Grinlok|r"
L["Omnis Grinlok Note"] = "包含60-80|cFFFFFFFF青銅幣|r."
L["Nalash Verdantis"] = "|cFFFFFFFFNalash Verdantis|r"
L["Nalash Verdantis Note"] = "包含60-80|cFFFFFFFF青銅幣|r."
L["Karr the Darkener"] = "|cFFFFFFFFKarr the Darkener|r"
L["Karr the Darkener Note"] = "包含60-80|cFFFFFFFF青銅幣|r."
L["Ai-Li Skymirror"] = "|cFFFFFFFFAi-Li Skymirror|r"
L["Ai-Li Skymirror Note"] = "包含60-80|cFFFFFFFF青銅幣|r."
L["Dak the Breaker"] = "|cFFFFFFFFDak the Breaker|r"
L["Dak the Breaker Note"] = "包含60-80|cFFFFFFFF青銅幣|r."
L["Zandalari Warbringer"] = "|cFFFFFFFF贊達拉戰爭使者|r"
L["Zandalari Warbringer Note"] = "包含60-80|cFFFFFFFF青銅幣|r以及聲望通貨。"

L["Klaxxi"] = "|cFFFFFFFF卡拉希|r"
L["Klaxxi Note"] = "兌換|cFFFFFFFF次級好運符|r 依據聲望。"

-- Isle of Thunder (Rare)
L["Ra'sha"] = "|cFFFFFFFFRa'sha|r"
L["Ra'sha Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["God-Hulk Ramuk"] = "|cFFFFFFFFGod-Hulk Ramuk|r"
L["God-Hulk Ramuk Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Goda"] = "|cFFFFFFFFGoda|r"
L["Goda Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Backbreaker Uru"] = "|cFFFFFFFFBackbreaker Uru|r"
L["Backbreaker Uru Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Lu-Ban"] = "|cFFFFFFFFLu-Ban|r"
L["Lu-Ban Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Mumta"] = "|cFFFFFFFFMumta|r"
L["Mumta Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Progenitus"] = "|cFFFFFFFFProgenitus|r"
L["Progenitus Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Ku'lai the Skyclaw"] = "|cFFFFFFFFKu'lai the Skyclaw|r"
L["Ku'lai the Skyclaw Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Al'tabim the All-Seeing"] = "|cFFFFFFFFAl'tabim the All-Seeing|r"
L["Al'tabim the All-Seeing Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Molthor"] = "|cFFFFFFFFMolthor|r"
L["Molthor Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Haywire Sunreaver Construct"] = "|cFFFFFFFFHaywire Sunreaver Construct|r"
L["Haywire Sunreaver Construct Note"] = "包含50-70|cFFFFFFFF青銅幣|r."

L["Kor'dok and Tinzo the Emberkeeper"] = "|cFFFFFFFFKor'dok and Tinzo the Emberkeeper|r"
L["Kor'dok and Tinzo the Emberkeeper Note"] = "包含 50-70 |cFFFFFFFF青銅幣|r, 需要三人來召喚|cFF0070DDShan'ze Ritual Stone|r."
L["Spirit of Warlord Teng"] = "|cFFFFFFFFSpirit of Warlord Teng|r"
L["Spirit of Warlord Teng Note"] = "包含 50-70 |cFFFFFFFF青銅幣|r, 需要三人來召喚|cFF0070DDShan'ze Ritual Stone|r."
L["Echo of Kros"] = "|cFFFFFFFFEcho of Kros|r"
L["Echo of Kros Note"] = "包含 50-70 |cFFFFFFFF青銅幣|r, 需要三人來召喚|cFF0070DDShan'ze Ritual Stone|r."
L["Electromancer Ju'le"] = "|cFFFFFFFFElectromancer Ju'le|r"
L["Electromancer Ju'le Note"] = "包含 50-70 |cFFFFFFFF青銅幣|r, 需要三人來召喚|cFF0070DDShan'ze Ritual Stone|r."
L["Qi'nor"] = "|cFFFFFFFFQi'nor|r"
L["Qi'nor Note"] = "包含 50-70 |cFFFFFFFF青銅幣|r, 需要三人來召喚|cFF0070DDShan'ze Ritual Stone|r."
L["Ancient Mogu Guardian"] = "|cFFFFFFFFAncient Mogu Guardian|r"
L["Ancient Mogu Guardian Note"] = "包含 50-70 |cFFFFFFFF青銅幣|r, 需要三人來召喚|cFF0070DDShan'ze Ritual Stone|r."
L["Incomplete Drakkari Colossus"] = "|cFFFFFFFFIncomplete Drakkari Colossus|r"
L["Incomplete Drakkari Colossus Note"] = "包含 50-70 |cFFFFFFFF青銅幣|r, 需要三人來召喚|cFF0070DDShan'ze Ritual Stone|r."
L["Cera"] = "|cFFFFFFFFCera|r"
L["Cera Note"] = "包含 50-70 |cFFFFFFFF青銅幣|r, 需要三人來召喚|cFF0070DDShan'ze Ritual Stone|r."
L["Windweaver Akil'amon"] = "|cFFFFFFFFWindweaver Akil'amon|r"
L["Windweaver Akil'amon Note"] = "包含 50-70 |cFFFFFFFF青銅幣|r, 需要三人來召喚|cFF0070DDShan'ze Ritual Stone|r."



-- Timeless Isle (Treasure)
L["Flameheart Shawl"] = "|cFFFFFFFFFlameheart Shawl|r"
L["Flameheart Shawl Note"] = "包含10-20 |cFFFFFFFF永恆幣|r。"
L["Riverspeaker's Trident"] = "|cFFFFFFFFRiverspeaker's Trident|r"
L["Riverspeaker's Trident Note"] = "包含10-20 |cFFFFFFFF永恆幣|r。"
L["Cloudstrike Family Helm"] = "|cFFFFFFFFCloudstrike Family Helm|r"
L["Cloudstrike Family Helm Note"] = "包含10-20 |cFFFFFFFF永恆幣|r。"
L["Snowdrift Tiger Talons"] = "|cFFFFFFFFSnowdrift Tiger Talons|r"
L["Snowdrift Tiger Talons Note"] = "包含10-20 |cFFFFFFFF永恆幣|r。"
L["Gleaming Treasure Chest"] = "|cFFFFFFFFGleaming Treasure Chest|r"
L["Gleaming Treasure Chest Note"] = "包含10-20 |cFFFFFFFF永恆幣|r。"
L["Rope-Bound Treasure Chest"] = "|cFFFFFFFFRope-Bound Treasure Chest|r"
L["Rope-Bound Treasure Chest Note"] = "包含10-20 |cFFFFFFFF永恆幣|r。"
L["Mist-Covered Treasure Chest"] = "|cFFFFFFFFMist-Covered Treasure Chest|r"
L["Mist-Covered Treasure Chest Note"] = "包含10-20 |cFFFFFFFF永恆幣|r。"
L["Sunken Treasure"] = "|cFFFFFFFFSunken Treasure|r"
L["Sunken Treasure Note"] = "包含10-20 |cFFFFFFFF永恆幣|r。"
L["Blackguard's Jetsam"] = "|cFFFFFFFFBlackguard's Jetsam|r"
L["Blackguard's Jetsam Note"] = "包含10-20 |cFFFFFFFF永恆幣|r。"
L["Gleaming Treasure Satchel"] = "|cFFFFFFFFGleaming Treasure Satchel|r"
L["Gleaming Treasure Satchel Note"] = "包含10-20 |cFFFFFFFF永恆幣|r。"

-- Timeless Isle (Rare)
L["Jadefire"] = "|cFFFFFFFFSpirit of Jadefire|r"
L["Jadefire Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Rattleskew"] = "|cFFFFFFFFRattleskew|r"
L["Rattleskew Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Cranegnasher"] = "|cFFFFFFFFCranegnasher|r"
L["Cranegnasher Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Spelurk"] = "|cFFFFFFFFSpelurk|r"
L["Spelurk Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Cah Silentsky"] = "|cFFFFFFFFCah Silentsky|r"
L["Cah Silentsky Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Chelon"] = "|cFFFFFFFFChelon|r"
L["Chelon Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Karkanos"] = "|cFFFFFFFFKarkanos|r"
L["Karkanos Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Zhu-Gon the Sour"] = "|cFFFFFFFFZhu-Gon the Sour|r"
L["Zhu-Gon the Sour Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Gu'chi the Swarmbringer"] = "|cFFFFFFFFGu'chi the Swarmbringer|r"
L["Gu'chi the Swarmbringer Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Zesqua"] = "|cFFFFFFFFZesqua|r"
L["Zesqua Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Emerald Gander"] = "|cFFFFFFFFEmerald Gander|r"
L["Emerald Gander Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Great Turtle Furyshell"] = "|cFFFFFFFFGreat Turtle Furyshell|r"
L["Great Turtle Furyshell Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Leafmender"] = "|cFFFFFFFFLeafmender|r"
L["Leafmender Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Ironfur Steelhorn"] = "|cFFFFFFFFIronfur Steelhorn|r"
L["Ironfur Steelhorn Note"] = "包含50-70|cFFFFFFFF青銅幣|r."

L["Rock Moss"] = "|cFFFFFFFFRock Moss|r"
L["Rock Moss Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Cinderfall"] = "|cFFFFFFFFCinderfall|r"
L["Cinderfall Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Stinkbraid"] = "|cFFFFFFFFStinkbraid|r"
L["Stinkbraid Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Garnia"] = "|cFFFFFFFFGarnia|r"
L["Garnia Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Tsavo'ka"] = "|cFFFFFFFFTsavo'ka|r"
L["Tsavo'ka Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Huolon"] = "|cFFFFFFFFHuolon|r"
L["Huolon Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Monstrous Spineclaw"] = "|cFFFFFFFFMonstrous Spineclaw|r"
L["Monstrous Spineclaw Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Bufo"] = "|cFFFFFFFFBufo|r"
L["Bufo Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Dread Ship Vazuvius"] = "|cFFFFFFFFDread Ship Vazuvius|r"
L["Dread Ship Vazuvius Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Golganarr"] = "|cFFFFFFFFGolganarr|r"
L["Golganarr Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Imperial Python"] = "|cFFFFFFFFImperial Python|r"
L["Imperial Python Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Evermaw"] = "|cFFFFFFFFEvermaw|r"
L["Evermaw Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Archiereus of Flame"] = "|cFFFFFFFFArchiereus of Flame|r"
L["Archiereus of Flame Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Watcher Osu"] = "|cFFFFFFFFWatcher Osu|r"
L["Watcher Osu Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Urdur the Cauterizer"] = "|cFFFFFFFFUrdur the Cauterizer|r"
L["Urdur the Cauterizer Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Jakur of Ordon"] = "|cFFFFFFFFJakur of Ordon|r"
L["Jakur of Ordon Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Flintlord Gairan"] = "|cFFFFFFFFFlintlord Gairan|r"
L["Flintlord Gairan Note"] = "包含50-70|cFFFFFFFF青銅幣|r."
L["Champion of the Black Flame"] = "|cFFFFFFFFChampion of the Black Flame|r"
L["Champion of the Black Flame Note"] = "包含50-70|cFFFFFFFF青銅幣|r."

-- Waypoints
L["Create waypoint"] = "建立路徑點"
L["Create all waypoints"] = "建立全部路徑點"
L["Hide node"] = "隱藏節點"
L["Close"] = "關閉"

-- Options
L["Icon settings"] = "圖示設定"
L["These settings control the look of the icon."] = true
L["Icon Scale"] = "圖示縮放"
L["The scale of the icons"] = true
L["Icon Alpha"] = "圖示透明度"
L["The alpha transparency of the icons"] = true
L["World Map"] = "世界地圖"
L["Show icons on world map"] = true
L["Minimap"] = "小地圖"
L["Show icons on the minimap"] = true
L["What to display"] = "那些要顯示"
L["Show Zamros"] = "顯示農金幣位置"
L["Show Zamros gold"] = "Show activity points with which you can earn gold"
L["Reset hidden nodes"] = "重置隱藏節點"
L["Show all nodes that you manually hid by right-clicking on them and choosing \"hide\"."] = true